[config]

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.hyprland]
input_path = './templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.nvim]
input_path = './templates/neovim.lua'
output_path = '~/.config/nvim/colors.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.rofi]
input_path = './templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.walker]
input_path = './templates/walker.css'
output_path = '~/.config/walker/themes/own/colors.css'

[templates.tmux]
input_path = './templates/tmux.conf'
output_path = '~/.tmux/colors.conf'
post_hook = 'tmux source-file ~/.tmux/theme.conf'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-<* if {{ is_dark_mode }}*>dark<* else *>light<* endif *>; gsettings set org.gnome.desktop.interface color-scheme <* if {{ is_dark_mode }}*>prefer-dark<* else *>prefer-light<* endif *>'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/colors.conf'

[templates.qt6ct]
input_path = './templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/colors.conf'

[templates.dunst]
input_path = './templates/dunst'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'

[templates.pywalfox]
input_path = './templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.zen-userChrome]
input_path = './templates/zen-userChrome.css'
output_path = '~/.zen/0z3de69z.Default (release)/chrome/userChrome.css'
post_hook = 'pkill -SIGUSR1 zen-bin'

[templates.zen-userContent]
input_path = './templates/zen-userContent.css'
output_path = '~/.zen/0z3de69z.Default (release)/chrome/userContent.css'
post_hook = 'pkill -SIGUSR1 zen-bin'

[templates.obsidian]
input_path = './templates/obsidian.css'
output_path = '~/secondbrane/.obsidian/snippets/theme.css'

